public enum Endpoint {
    CREATE_TASK,
    CREATE_UPDATE_TASK,
    GET_ALL_TASKS,
    GET_TASK_BY_ID,
    DELETE_ALL_TASKS,
    DELETE_TASK_BY_ID,
    GET_ALL_SUBTASKS_BY_EPIC,
    ADD_SUBTASK_TO_EPIC,
    GET_HISTORY,
    GET_PRIORITIZED,
    UNKNOWN
}
